"""make video filename nullable for retention

Revision ID: b8975578a898
Revises: 0669d4399e6f
Create Date: 2026-07-19 22:49:47.682003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8975578a898'
down_revision: Union[str, Sequence[str], None] = '0669d4399e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analyses', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analyses', schema=None) as batch_op:
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
