"""add analysis_data column

Revision ID: f843b9488478
Revises: b8975578a898
Create Date: 2026-07-20 10:58:12.973373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f843b9488478'
down_revision: Union[str, Sequence[str], None] = 'b8975578a898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video_analyses', schema=None) as batch_op:
        batch_op.drop_column('analysis_data')

    # ### end Alembic commands ###
